### ISSUE TITLE
Function to subtract and add funds to players bank

### ISSUE THREAD

**Issue by BrianV1981** [gruppe-adler/grad-listBuymenu#24]
Hello McDiod, 
I was looking for a way to add and subtract funds from a player's bank account.

Thanks,
Brian V.

**Comment by Fusselwurm** [comment]
that's implemented in https://github.com/gruppe-adler/grad-moneyMenu see for example https://github.com/gruppe-adler/grad-moneyMenu/wiki/addFunds

**Comment by McDiod** [comment]
Bank accounts are different. Looks like there is no function for that yet.

**Comment by McDiod** [comment]
This is now implemented in [grad-moneymenu 0.3.2](https://github.com/gruppe-adler/grad-moneyMenu/releases/tag/0.3.2). This is *not* implemented in grad-listbuymenu, because bank accounts are not a feature in this module.

https://github.com/gruppe-adler/grad-moneyMenu/wiki/addFunds
https://github.com/gruppe-adler/grad-moneyMenu/wiki/getFunds
https://github.com/gruppe-adler/grad-moneyMenu/wiki/setFunds
