### ISSUE TITLE
Adding an "Other" Category's Code Question

### ISSUE THREAD

**Issue by RaidenKoizuma** [gruppe-adler/grad-listBuymenu#25]
I'm a bit confused on how to put in code for Other. I want the player to purchase the thing and have it execute the following code onto them, but I can't seem to get it to work. Without this snippet inserted, everything works just fine.

	class Other {
            displayName = "G. Buildable";
            kindOf = "Other";
		class Land_TentA_F {
                price = 20;
                stock = 100;
		code = "[_this,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort";
            };
        };

I know it's probably something to do with the passed parameters, but I'm confused how to go about that. Sorry, I know this is probably super easy and I'm just dense. I've tried messing with it but still can't get it to work.

**Comment by McDiod** [comment]
The parameter variable `_this` contains different things depending on the items category (see [here](https://github.com/gruppe-adler/grad-listBuymenu/wiki/Configuration#code)). In your case (`other`) it contains `[buyer, item class name]`, so with [grad_fortifications_fnc_addFort](https://github.com/gruppe-adler/grad-fortifications/wiki/addFort) we need:

```sqf
code = "[_this select 0, _this select 1] call grad_fortifications_fnc_addFort";
```
or simply
```sqf
code = "_this call grad_fortifications_fnc_addFort";
```

to add a `Land_TentA_F` to the buyer.

Now because this is always executed on both the buyer's machine and the server, you would actually add two tents, so we need to do this:

```sqf
code = "if (isServer) then {_this call grad_fortifications_fnc_addFort}";
```

*** 

Also there is a syntax error in your example. Quotation marks within quotation marks work like this:
```
code = "[_this,'Land_BagFence_Corner_F'] call grad_fortifications_fnc_addFort";
```

**Comment by RaidenKoizuma** [comment]
Hey yeah, it works! I'm using code = "if (isServer) then {_this call grad_fortifications_fnc_addFort}"; and it works great! Thanks a bunch!
